/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ApiVoidrideRouteImport } from './routes/api/voidride'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoidrideRoute = ApiVoidrideRouteImport.update({
  id: '/api/voidride',
  path: '/api/voidride',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/live': typeof ApiLiveRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/voidride': typeof ApiVoidrideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/live': typeof ApiLiveRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/voidride': typeof ApiVoidrideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/live': typeof ApiLiveRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/voidride': typeof ApiVoidrideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/live' | '/api/rtc' | '/api/voidride'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/live' | '/api/rtc' | '/api/voidride'
  id: '__root__' | '/' | '/api/live' | '/api/rtc' | '/api/voidride'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiLiveRoute: typeof ApiLiveRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiVoidrideRoute: typeof ApiVoidrideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voidride': {
      id: '/api/voidride'
      path: '/api/voidride'
      fullPath: '/api/voidride'
      preLoaderRoute: typeof ApiVoidrideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiLiveRoute: ApiLiveRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiVoidrideRoute: ApiVoidrideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
